name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install --production=false
      - name: Run production build
        env:
          CI: false
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: uig-prod-build
          path: build
