name: Deploy to production
on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install modules
        run: npm install --production=true
      - name: Run production build
        run: npm run build
      - name: Install S3 CLI
        run: sudo npm i -g s3-deploy
      - name: Deploy to S3
        run: s3-deploy \
          './build/**' \
          --cwd './' \
          --bucket ${{ secrets.S3_BUCKET }} \
          --distId ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --etag \
          --gzip xml,html,htm,js,json,css,ttf,otf,svg,txt \
          --invalidate '/*' \
          --noCache
